### ISSUE TITLE
Stop Timer if menu accessed 

### ISSUE THREAD

**Issue by SeanDunford** [SeanDunford/Tempo-WatchKit#28]
Stop Timer if menu asked. 

Not sure on the exact functionality of this but we need to stop the timer if they hit menu.

**Comment by alphastory** [comment]
Right now I'm pausing the timer when the menu is open and resuming when its closed. Do you think this works? Should we clear the timer in general?

**Comment by SeanDunford** [comment]
Wont be in issue when we add #36 Morph menu task
