### ISSUE TITLE
Should we add a pause/start mode? 

### ISSUE THREAD

**Issue by SeanDunford** [SeanDunford/Tempo-WatchKit#29]
Should we add a mode to start/stop the timer at will?

**Comment by SeanDunford** [comment]
![img_1320 png copy](https://cloud.githubusercontent.com/assets/1704718/6095933/4a24838a-af2a-11e4-9609-fa1c2c0e0764.png)

**Comment by SeanDunford** [comment]
Obviously Pause, Current Interval and Stop would be aligned.

**Comment by alphastory** [comment]
I could get behind something like that, except switch the "Pause", "Interval" and "Stop" text to the gray in the launch screen.

**Comment by SeanDunford** [comment]
Going to morph menu into the x button will add middle screen touch pause.
