### ISSUE TITLE
Sounds we need sounds

### ISSUE THREAD

**Issue by SeanDunford** [SeanDunford/Tempo-WatchKit#31]

**Comment by SeanDunford** [comment]
https://www.freesound.org/people/Shot846/sounds/131006/

**Comment by alphastory** [comment]
Don't make fun of me for this chunk of code:

var filePath:NSString!
if( soundPath == "short" ){
    filePath = NSBundle.mainBundle().pathForResource("short", ofType: "wav");
} else if( soundPath == "long" ){
    filePath = NSBundle.mainBundle().pathForResource("long", ofType: "wav");
}

I'm aware I could simply do:

    filePath = NSBundle.mainBundle().pathForResource(soundPath, ofType: "wav");

But I was having tons of issues getting that to work, so I hacked it up. If you can make it pretty, please do.
