### ISSUE TITLE
Handle on Circle slider is too small

### ISSUE THREAD

**Issue by SeanDunford** [SeanDunford/Tempo-WatchKit#32]
Maybe not design wise but we should at least increase it's grabbable radius. It's too bad that you grab it and it doesn't always spin.

**Comment by alphastory** [comment]
I experienced the same issue with the grabbable radius. Not sure how to increase that. I tried increasing the size of the handle itself, but that didn't solve the problem.

**Comment by SeanDunford** [comment]
Fixed with last pull request. Though, Should we increase the size of the handle from a UI perspective?
